version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "6541:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

  server:
    build: wise-server
    image: qq6k/wms-server:1.0
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wise
      - POSTGRES_DB=wise
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  client:
    build: wise-front
    image: qq6k/wms-frontend:1.0
    container_name: wise-front
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true