version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: miss-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=miss
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: server
    image: qq6k/wms-server:1.0
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/miss
      - POSTGRES_DB=miss
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  client:
    build: miss-front
    image: qq6k/wms-frontend:1.0
    container_name: miss-front
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true