insert INTO ITEMS (id,name, price, amount) values(default,'Дрель кондитерская', 55.20, 5);
insert INTO ITEMS (id,name, price, amount) values(default,'Морская кладь', 160.15, 0);
insert INTO ITEMS (id,name, price, amount) values(default,'Быстронаживное дело', 10.00, 100);
insert INTO ITEMS (id,name, price, amount) values(default,'Итерационный луч', 99.99, 1);
insert INTO ITEMS (id,name, price, amount) values(default,'Роман Широков', 1234.56, 1);
insert INTO ITEMS (id,name, price, amount) values(default,'Киндер сюрприз', 200.00, 101);
insert INTO ITEMS (id,name, price, amount) values(default,'Буква Ю без перекладины (I0)', 300, 500);
insert INTO ITEMS (id,name, price, amount) values(default,'Гвоздь Маяковского', 1.15, 1000000);
insert INTO ITEMS (id,name, price, amount) values(default,'Астон Мартин DB6', 100000.00,2);
insert INTO ITEMS (id,name, price, amount) values(default,'Аспирин для котов', 0.25, 20);
insert INTO ITEMS (id,name, price, amount) values(default,'Телеграмма Дмитрию Киселеву', 0.25,1);