insert INTO ITEMS (id,name, price) values(default,'Дрель кондитерская', 55.20);
insert INTO ITEMS (id,name, price) values(default,'Морская кладь', 160.15);
insert INTO ITEMS (id,name, price) values(default,'Быстронаживное дело', 10.00);
insert INTO ITEMS (id,name, price) values(default,'Итерационный луч', 99.99);
insert INTO ITEMS (id,name, price) values(default,'Роман Широков', 1234.56);
insert INTO ITEMS (id,name, price) values(default,'Киндер сюрприз', 200.00);
insert INTO ITEMS (id,name, price) values(default,'Буква Ю без перекладины (I0)', 300);
insert INTO ITEMS (id,name, price) values(default,'Гвоздь Маяковского', 1.15);
insert INTO ITEMS (id,name, price) values(default,'Астон Мартин DB6', 100000.00);
insert INTO ITEMS (id,name, price) values(default,'Аспирин для котов', 0.25);
insert INTO ITEMS (id,name, price) values(default,'Телеграмма Дмитрию Киселеву', 0.25);