drop table if exists discounts cascade;
drop table if exists items cascade;
drop table if exists itemSales cascade;
drop table if exists Sales cascade;

CREATE TABLE IF NOT EXISTS items
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR(128)                            NOT NULL,
    price double                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS discounts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    val_coefficient DOUBLE                                  NOT NULL,
    item_id         BIGINT                                  NOT null REFERENCES items (id),
    starting        timestamp                               not null,
    ending          timestamp                               not null
);

CREATE TABLE IF NOT EXISTS basket
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created_on    TIMESTAMP DEFAULT NOW(),
    basketItem_id BIGINT
);

CREATE TABLE IF NOT EXISTS basketItems
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    item_id    BIGINT                                  NOT null REFERENCES items (id),
    count      SMALLINT                                NOT NULL,
    created_on TIMESTAMP DEFAULT NOW(),
    basket_id  BIGINT                                  NOT null REFERENCES basket (id)
);

CREATE TABLE IF NOT EXISTS orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created_on   TIMESTAMP DEFAULT NOW(),
    orderItem_id BIGINT                                  NOT NULL,
    totalAmount  DOUBLE                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS orderItems
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    item_id        BIGINT                                  NOT null REFERENCES items (id),
    fixedItemPrice DOUBLE                                  NOT NULL,
    count          SMALLINT                                NOT NULL,
    basket_id      BIGINT                                  NOT null REFERENCES orders (id)
);


INSERT INTO ITEMS
values (1, 'Дрель кондитерская', 55.20),
       (2, 'Морская кладь', 160.15),
       (3, 'Быстронаживное дело', 10.00),
       (4, 'Итерационный луч', 99.99),
       (5, 'Роман Широков', 1234.56),
       (6, 'Киндер сюрприз', 200.00),
       (7, 'Буква Ю без перекладины (I0)', 300),
       (8, 'Гвоздь Маяковского', 1.15),
       (9, 'Астон Мартин DB6', 100000.00),
       (10, 'Аспирин для котов', 0.25)